version: "3"

services:

  # Redis
  redis:
    build: ../redis
    container_name: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"
    networks:
      - mynet

  cron:
    links:
      - redis
      - db